services:
    backend:
        build: ./backend
        volumes:
            - ./backend:/app
        ports:
            - '8000:8000'
        depends_on:
            - db

    frontend:
        build: ./frontend
        volumes:
            - ./frontend:/app/frontend
            - /app/frontend/node_modules
        ports:
            - '5173:5173'
        stdin_open: true
        tty: true

    db:
        image: mysql:8.0
        env_file:
            - .env
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - '3307:3306'
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
